x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:

  ############################################################
  # IMMICH — Gestión de Fotos y Vídeos Personales
  ############################################################
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /mnt/datos_docker/immich/upload:/usr/src/app/upload
      - /mnt/datos_docker:/mnt/media_externa:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_HOSTNAME=immich-postgres
      - REDIS_HOSTNAME=immich-redis
    env_file: .env
    ports:
      - "18000:2283"
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-postgres:
        condition: service_healthy
    restart: always
    networks:
      - media
    logging: *default-logging

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - immich-ml-cache:/cache
    environment:
      - IMMICH_WORKERS=1
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2048M
    env_file: .env
    restart: always
    networks:
      - media
    logging: *default-logging

  immich-redis:
    image: redis:7-alpine
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - media
    logging: *default-logging

  immich-postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /mnt/datos_docker/immich/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME} || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - media
    logging: *default-logging

############################################################
# REDES Y VOLÚMENES EXTERNOS
############################################################
networks:
  media:
    name: media_network

volumes:
  immich-ml-cache:
