services:
  portainer:
    # Intentionally using :latest for homelab auto-updates
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - "127.0.0.1:19443:9443" # HTTPS Web UI
      #- "127.0.0.1:18000:8000" # Only required if adding Edge Nodes (optional)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"