services:
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb-app
    ports:
      - 8080:8080
    environment:
      - NC_TOOL_DIR=/usr/app/data
      - NC_REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/usr/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - ./redis:/data
    restart: unless-stopped