version: "3.8"

services:
  blocky:
    image: spx01/blocky:${BLOCKY_VERSION:-latest}
    # ELIMINADO: container_name: blocky_dns (para mantener consistencia con el resto del repo)
    env_file:
      - .env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp" # Puerto para la API HTTP y métricas
    environment:
      - TZ=${TZ}
    volumes:
      - ./config.yml:/app/config.yml:ro # Solo lectura (GitOps manda)
    restart: unless-stopped