version: "3.8"

services:
  blocky:
    image: spx01/blocky:${BLOCKY_VERSION:-latest}
    env_file:
      - .env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "127.0.0.1:4000:4000/tcp" # API atada a loopback por seguridad
    environment:
      - TZ=${TZ}
    volumes:
      - ./config.yml:/app/config.yml:ro # Solo lectura (GitOps manda)
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"